version: '3.8'
services:
  appfront:
    container_name: appfront
    build: 
      context: .
      dockerfile: Dockerfile
    image: appfront:latest
    ports:
      - "81:80"
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
